/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.1.11-6-ga9c1ef2626"
#endif /* AVUTIL_FFVERSION_H */
