/* DO NOT EDIT THIS FILE - it is machine generated */
#import "LibInit.h"


#ifndef _Included_com_zq_playerlib_ZQPusher
#define _Included_com_zq_playerlib_ZQPusher
#ifdef __cplusplus
extern "C" {
#import <libavformat/avformat.h>
#import "libavutil/imgutils.h"
#import "libavutil/time.h"
#endif
class Pusher {
public:
    JavaVM *javaVM;
    const char *url;
    int width;
    int height;
    int fps = 15;
    int yuv_width;
    int yuv_height;
    int y_length;
    int uv_length;
    AVFormatContext *ofmt_ctx;
    AVCodec *pCodec;
    AVCodecContext *pCodecCtx;
    AVStream *video_st;
    AVFrame *pFrameYUV;
    int count = 0;
    AVPacket enc_pkt;
public:
    Pusher(JavaVM *javaVM);
    int init(const char *url, int width, int height);
    int onFrameCallback(JNIEnv *env, jbyteArray data);
};



/*
 * Class:     com_zq_playerlib_ZQPusher
 * Method:    initVideo
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_zq_playerlib_ZQPusher_initVideo
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_zq_playerlib_ZQPusher
 * Method:    onFrameCallback
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_zq_playerlib_ZQPusher_onFrameCallback
  (JNIEnv *, jobject, jbyteArray);

JNIEXPORT jint JNICALL Java_com_zq_playerlib_ZQPusher_pushVideo
        (JNIEnv *env, jobject instance, jstring videoFilePath, jstring pushUrl);

#ifdef __cplusplus
}
#endif
#endif
